import { useEffect } from "react";

import Head from "next/head";
import styles from "styles/Home.module.scss";
import { gsap } from "gsap";
import { Text_animation } from "pages/components/molecules/text_animation";

export const About = () => {
  useEffect(() => {
    gsap.from("#title", {
      opacity: 0,
      y: 60,
      duration: 1,
    });
  });
  return (
    <div className={`${styles.container} ${styles.bgbk}`}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Template />
      <Tomato /> */}
      <h1 id="title" className={styles.white}>
        About
      </h1>
    </div>
  );
};
