import Head from "next/head";
import styles from "styles/Home.module.scss";
import { Home as Template } from "pages/components/templates/home";
import { Tomato } from "pages/components/atoms/tomato";

export const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template />
      <Tomato />
    </div>
  );
};
